name: Application Build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable yarn berry
        run: corepack enable
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          cache: yarn
          # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: yarn.lock
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 22.x
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: yarn build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
